# To use:
#
#     pre-commit run --all-files  # run all hooks on all files
#     pre-commit run <HOOK_ID> --all-files  # run one hooks on all files
#     pre-commit run --files <path_to_file> <path_to_folder/**>  # run all hook on files
#     pre-commit run <HOOK_ID> --files <path_to_file> <path_to_folder/**>  # run one hook on files
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

# Detect hardcoded secrets and ocids in notebook_examples/ folder
repos:
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.17.0
    hooks:
    -   id: gitleaks
        files: ^notebook_examples/
# Oracle copyright checkers in notebook_examples/ folder
-   repo: local
    hooks:
    -   id: check-copyright
        name: check-copyright
        entry: .pre-commit-scripts/check-copyright.py
        language: script
        types_or: ['python', 'shell', 'bash']
        files: ^notebook_examples/
